### ISSUE TITLE
W (1579) phy_init: failed to load RF calibration data (0x1102), falling back to full calibration

### ISSUE THREAD

**Issue by ChenHuaYou** [nopnop2002/esp-idf-http-camera#3]
W (1579) phy_init: failed to load RF calibration data (0x1102), falling back to full calibration

hi, after compile the project step by step writting in the readme, idf.py -p /dev/ttyUSB0 monitor give me this error .

**Comment by ChenHuaYou** [comment]
i finally figure out that is the power setting problem.

**Comment by nopnop2002** [comment]
esp32-cam requires a lot of current.
